/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gherynos_libsaltpack_MessageWriter */

#ifndef _Included_com_gherynos_libsaltpack_MessageWriter
#define _Included_com_gherynos_libsaltpack_MessageWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gherynos_libsaltpack_MessageWriter
 * Method:    constructor
 * Signature: (Lcom/gherynos/libsaltpack/OutputParameters;[B[[BZ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_gherynos_libsaltpack_MessageWriter_constructor__Lcom_gherynos_libsaltpack_OutputParameters_2_3B_3_3BZ
  (JNIEnv *, jobject, jobject, jbyteArray, jobjectArray, jboolean);

/*
 * Class:     com_gherynos_libsaltpack_MessageWriter
 * Method:    constructor
 * Signature: (Lcom/gherynos/libsaltpack/OutputParameters;[B[[B)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_gherynos_libsaltpack_MessageWriter_constructor__Lcom_gherynos_libsaltpack_OutputParameters_2_3B_3_3B
  (JNIEnv *, jobject, jobject, jbyteArray, jobjectArray);

/*
 * Class:     com_gherynos_libsaltpack_MessageWriter
 * Method:    constructor
 * Signature: (Lcom/gherynos/libsaltpack/OutputParameters;[[BZ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_gherynos_libsaltpack_MessageWriter_constructor__Lcom_gherynos_libsaltpack_OutputParameters_2_3_3BZ
  (JNIEnv *, jobject, jobject, jobjectArray, jboolean);

/*
 * Class:     com_gherynos_libsaltpack_MessageWriter
 * Method:    constructor
 * Signature: (Lcom/gherynos/libsaltpack/OutputParameters;[[B)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_gherynos_libsaltpack_MessageWriter_constructor__Lcom_gherynos_libsaltpack_OutputParameters_2_3_3B
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_gherynos_libsaltpack_MessageWriter
 * Method:    constructor
 * Signature: (Lcom/gherynos/libsaltpack/OutputParameters;[BZ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_gherynos_libsaltpack_MessageWriter_constructor__Lcom_gherynos_libsaltpack_OutputParameters_2_3BZ
  (JNIEnv *, jobject, jobject, jbyteArray, jboolean);

/*
 * Class:     com_gherynos_libsaltpack_MessageWriter
 * Method:    constructor
 * Signature: (Lcom/gherynos/libsaltpack/OutputParameters;[B[[B[[[B)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_gherynos_libsaltpack_MessageWriter_constructor__Lcom_gherynos_libsaltpack_OutputParameters_2_3B_3_3B_3_3_3B
  (JNIEnv *, jobject, jobject, jbyteArray, jobjectArray, jobjectArray);

/*
 * Class:     com_gherynos_libsaltpack_MessageWriter
 * Method:    constructor
 * Signature: (Lcom/gherynos/libsaltpack/OutputParameters;[[B[[[B)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_gherynos_libsaltpack_MessageWriter_constructor__Lcom_gherynos_libsaltpack_OutputParameters_2_3_3B_3_3_3B
  (JNIEnv *, jobject, jobject, jobjectArray, jobjectArray);

/*
 * Class:     com_gherynos_libsaltpack_MessageWriter
 * Method:    destructor
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_gherynos_libsaltpack_MessageWriter_destructor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_gherynos_libsaltpack_MessageWriter
 * Method:    addBlock
 * Signature: (Ljava/nio/ByteBuffer;[BIIZ)V
 */
JNIEXPORT void JNICALL Java_com_gherynos_libsaltpack_MessageWriter_addBlock
  (JNIEnv *, jobject, jobject, jbyteArray, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
