/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_nharyes_libsaltpack_MessageReader */

#ifndef _Included_net_nharyes_libsaltpack_MessageReader
#define _Included_net_nharyes_libsaltpack_MessageReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_nharyes_libsaltpack_MessageReader
 * Method:    constructor
 * Signature: (Lnet/nharyes/libsaltpack/InputParameters;[B)J
 */
JNIEXPORT jlong JNICALL Java_net_nharyes_libsaltpack_MessageReader_constructor__Lnet_nharyes_libsaltpack_InputParameters_2_3B
        (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     net_nharyes_libsaltpack_MessageReader
 * Method:    constructor
 * Signature: (Lnet/nharyes/libsaltpack/InputParameters;)J
 */
JNIEXPORT jlong JNICALL Java_net_nharyes_libsaltpack_MessageReader_constructor__Lnet_nharyes_libsaltpack_InputParameters_2
        (JNIEnv *, jobject, jobject);

/*
 * Class:     net_nharyes_libsaltpack_MessageReader
 * Method:    constructor
 * Signature: (Lnet/nharyes/libsaltpack/InputParameters;Ljava/io/InputStream;)J
 */
JNIEXPORT jlong JNICALL Java_net_nharyes_libsaltpack_MessageReader_constructor__Lnet_nharyes_libsaltpack_InputParameters_2Ljava_io_InputStream_2
        (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     net_nharyes_libsaltpack_MessageReader
 * Method:    destructor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_nharyes_libsaltpack_MessageReader_destructor
        (JNIEnv *, jobject, jlong);

/*
 * Class:     net_nharyes_libsaltpack_MessageReader
 * Method:    hasMoreBlocks
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_net_nharyes_libsaltpack_MessageReader_hasMoreBlocks
        (JNIEnv *, jobject, jlong);

/*
 * Class:     net_nharyes_libsaltpack_MessageReader
 * Method:    getBlock
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_nharyes_libsaltpack_MessageReader_getBlock
        (JNIEnv *, jobject, jlong);

/*
 * Class:     net_nharyes_libsaltpack_MessageReader
 * Method:    getRecipients
 * Signature: (J)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_net_nharyes_libsaltpack_MessageReader_getRecipients
        (JNIEnv *, jobject, jlong);

/*
 * Class:     net_nharyes_libsaltpack_MessageReader
 * Method:    getSender
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_nharyes_libsaltpack_MessageReader_getSender
        (JNIEnv *, jobject, jlong);

/*
 * Class:     net_nharyes_libsaltpack_MessageReader
 * Method:    isIntentionallyAnonymous
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_net_nharyes_libsaltpack_MessageReader_isIntentionallyAnonymous
        (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
