/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_nharyes_libsaltpack_MessageReader */

#ifndef _Included_net_nharyes_libsaltpack_MessageReader
#define _Included_net_nharyes_libsaltpack_MessageReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_nharyes_libsaltpack_MessageReader
 * Method:    constructor
 * Signature: (Lnet/nharyes/libsaltpack/InputParameters;[B)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_net_nharyes_libsaltpack_MessageReader_constructor__Lnet_nharyes_libsaltpack_InputParameters_2_3B
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     net_nharyes_libsaltpack_MessageReader
 * Method:    constructor
 * Signature: (Lnet/nharyes/libsaltpack/InputParameters;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_net_nharyes_libsaltpack_MessageReader_constructor__Lnet_nharyes_libsaltpack_InputParameters_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_nharyes_libsaltpack_MessageReader
 * Method:    constructor
 * Signature: (Lnet/nharyes/libsaltpack/InputParameters;Ljava/io/InputStream;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_net_nharyes_libsaltpack_MessageReader_constructor__Lnet_nharyes_libsaltpack_InputParameters_2Ljava_io_InputStream_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     net_nharyes_libsaltpack_MessageReader
 * Method:    constructor
 * Signature: (Lnet/nharyes/libsaltpack/InputParameters;[B[[B)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_net_nharyes_libsaltpack_MessageReader_constructor__Lnet_nharyes_libsaltpack_InputParameters_2_3B_3_3B
  (JNIEnv *, jobject, jobject, jbyteArray, jobjectArray);

/*
 * Class:     net_nharyes_libsaltpack_MessageReader
 * Method:    destructor
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_nharyes_libsaltpack_MessageReader_destructor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_nharyes_libsaltpack_MessageReader
 * Method:    hasMoreBlocks
 * Signature: (Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_nharyes_libsaltpack_MessageReader_hasMoreBlocks
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_nharyes_libsaltpack_MessageReader
 * Method:    getBlock
 * Signature: (Ljava/nio/ByteBuffer;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_nharyes_libsaltpack_MessageReader_getBlock
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_nharyes_libsaltpack_MessageReader
 * Method:    getRecipients
 * Signature: (Ljava/nio/ByteBuffer;)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_net_nharyes_libsaltpack_MessageReader_getRecipients
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_nharyes_libsaltpack_MessageReader
 * Method:    getSender
 * Signature: (Ljava/nio/ByteBuffer;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_nharyes_libsaltpack_MessageReader_getSender
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_nharyes_libsaltpack_MessageReader
 * Method:    isIntentionallyAnonymous
 * Signature: (Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_nharyes_libsaltpack_MessageReader_isIntentionallyAnonymous
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
