/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_nharyes_libsaltpack_MessageWriter */

#ifndef _Included_net_nharyes_libsaltpack_MessageWriter
#define _Included_net_nharyes_libsaltpack_MessageWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_nharyes_libsaltpack_MessageWriter
 * Method:    constructor
 * Signature: (Lnet/nharyes/libsaltpack/OutputParameters;[B[[BZ)J
 */
JNIEXPORT jlong JNICALL Java_net_nharyes_libsaltpack_MessageWriter_constructor__Lnet_nharyes_libsaltpack_OutputParameters_2_3B_3_3BZ
  (JNIEnv *, jobject, jobject, jbyteArray, jobjectArray, jboolean);

/*
 * Class:     net_nharyes_libsaltpack_MessageWriter
 * Method:    constructor
 * Signature: (Lnet/nharyes/libsaltpack/OutputParameters;[B[[B)J
 */
JNIEXPORT jlong JNICALL Java_net_nharyes_libsaltpack_MessageWriter_constructor__Lnet_nharyes_libsaltpack_OutputParameters_2_3B_3_3B
  (JNIEnv *, jobject, jobject, jbyteArray, jobjectArray);

/*
 * Class:     net_nharyes_libsaltpack_MessageWriter
 * Method:    constructor
 * Signature: (Lnet/nharyes/libsaltpack/OutputParameters;[[BZ)J
 */
JNIEXPORT jlong JNICALL Java_net_nharyes_libsaltpack_MessageWriter_constructor__Lnet_nharyes_libsaltpack_OutputParameters_2_3_3BZ
  (JNIEnv *, jobject, jobject, jobjectArray, jboolean);

/*
 * Class:     net_nharyes_libsaltpack_MessageWriter
 * Method:    constructor
 * Signature: (Lnet/nharyes/libsaltpack/OutputParameters;[[B)J
 */
JNIEXPORT jlong JNICALL Java_net_nharyes_libsaltpack_MessageWriter_constructor__Lnet_nharyes_libsaltpack_OutputParameters_2_3_3B
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     net_nharyes_libsaltpack_MessageWriter
 * Method:    constructor
 * Signature: (Lnet/nharyes/libsaltpack/OutputParameters;[BZ)J
 */
JNIEXPORT jlong JNICALL Java_net_nharyes_libsaltpack_MessageWriter_constructor__Lnet_nharyes_libsaltpack_OutputParameters_2_3BZ
  (JNIEnv *, jobject, jobject, jbyteArray, jboolean);

/*
 * Class:     net_nharyes_libsaltpack_MessageWriter
 * Method:    destructor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_nharyes_libsaltpack_MessageWriter_destructor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_nharyes_libsaltpack_MessageWriter
 * Method:    addBlock
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_net_nharyes_libsaltpack_MessageWriter_addBlock
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     net_nharyes_libsaltpack_MessageWriter
 * Method:    finalise
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_nharyes_libsaltpack_MessageWriter_finalise
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
