# Once done these will be defined:
#
# LIBSALTPACK_FOUND
# LIBSALTPACK_INCLUDE_DIRS
# LIBSALTPACK_LIBRARIES
#

if (LIBSALTPACK_INCLUDE_DIRS AND LIBSALTPACK_LIBRARIES)
    # Already in cache, be silent
    set(LIBSALTPACK_FIND_QUIETLY TRUE)
endif (LIBSALTPACK_INCLUDE_DIRS AND LIBSALTPACK_LIBRARIES)

find_path(LIBSALTPACK_INCLUDE_DIRS NAMES saltpack.h saltpack/Base.h)
find_library(LIBSALTPACK_LIBRARIES NAMES saltpack)
MESSAGE(STATUS "Saltpack libs: " ${LIBSALTPACK_LIBRARIES})

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBSALTPACK DEFAULT_MSG LIBSALTPACK_INCLUDE_DIRS LIBSALTPACK_LIBRARIES)

mark_as_advanced(LIBSALTPACK_INCLUDE_DIRS LIBSALTPACK_LIBRARIES)