---
# yamllint disable rule:line-length
default_language_version:
  python: python3
exclude: (CMakeFiles|cmake_modules|docs|target)\/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-xml
      - id: check-added-large-files
      - id: pretty-format-json
        args:
          - --autofix
      - id: detect-private-key
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: forbid-tabs
        exclude_types:
          - javascript
          - dtd
          - markdown
          - makefile
          - xml
          - css
        exclude: binary|\.bin$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint
  - repo: https://github.com/gherynos/pre-commit-java
    rev: v0.2.0
    hooks:
      - id: pmd
        exclude: /test/
        args: ["-R", "ruleset.xml", "-cache", "pmd.cache"]
