---
# yamllint disable rule:line-length
language: cpp

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - openjdk-8-jdk
            - maven
            - xz-utils
            - m4
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: osx
      osx_image: xcode10.1
      compiler: clang

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then eval "${MATRIX_EVAL}"; fi

addons:
  homebrew:
    packages:
      - libsodium
      - msgpack
    update: true

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then wget https://github.com/msgpack/msgpack-c/releases/download/cpp-2.0.0/msgpack-2.0.0.tar.gz; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then tar -xvzf msgpack-2.0.0.tar.gz; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then pushd msgpack-2.0.0 && cmake . && make && sudo make install && popd; fi

  - if [ $TRAVIS_OS_NAME = linux ]; then wget https://github.com/jedisct1/libsodium/releases/download/1.0.9/libsodium-1.0.9.tar.gz; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then tar -xvzf libsodium-1.0.9.tar.gz; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then pushd libsodium-1.0.9 && ./configure --with-pic && make && sudo make install && popd; fi

script:
  - wget https://github.com/gherynos/libsaltpack/archive/v0.3.1.tar.gz
  - tar -xvzf v0.3.1.tar.gz
  - pushd libsaltpack-0.3.1 && git clone https://github.com/983/Num.git ext/Num
  - cmake . && make && make test && sudo make install && popd

  - mvn compile
  - cmake -DJAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 .
  - make
  - mvn exec:java -Dexec.mainClass="net.nharyes.libsaltpack.Loader"

  - if [ $TRAVIS_OS_NAME = linux ]; then rm libsaltpack-jni.so; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then rm libsaltpack-jni.dylib; fi

  - mvn test

after_success:
  - mvn jacoco:report coveralls:report
