---
name: build

on:
  push:
  release:
    types: [created]

jobs:
  unix:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14]
        include:
          - os: ubuntu-22.04
            java_home: /usr/lib/jvm/java-17-openjdk-amd64
            library: libsaltpack-jni.so
          - os: macos-13
            java_home: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
            library: libsaltpack-jni.dylib
          - os: macos-14
            java_home: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
            library: libsaltpack-jni.dylib
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - if: runner.os == 'Linux'
        name: Linux dependencies
        run: |
          sudo apt-get install -y build-essential wget cmake openjdk-17-jdk maven xz-utils m4

      - if: runner.os == 'macOS'
        name: macOS dependencies
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: |
          brew tap homebrew/cask-versions
          brew install --cask temurin17

      - name: boost
        run: |
          wget https://boostorg.jfrog.io/artifactory/main/release/1.84.0/source/boost_1_84_0.tar.gz
          tar -xzf boost_1_84_0.tar.gz
          mv boost_1_84_0 boost_libs

      - name: MsgPack
        run: |
          wget https://github.com/msgpack/msgpack-c/releases/download/cpp-6.1.0/msgpack-cxx-6.1.0.tar.gz
          tar -xvzf msgpack-cxx-6.1.0.tar.gz
          pushd msgpack-cxx-6.1.0
          cmake -DMSGPACK_CXX14=ON -DBoost_INCLUDE_DIR=../boost_libs .
          sudo cmake --build . --target install
          popd

      - name: LibSodium
        run: |
          wget https://github.com/jedisct1/libsodium/releases/download/1.0.19-RELEASE/libsodium-1.0.19.tar.gz
          tar -xvzf libsodium-1.0.19.tar.gz
          pushd libsodium-stable
          ./configure --with-pic
          make
          sudo make install
          popd

      - name: LibSaltpack
        run: |
          wget https://github.com/gherynos/libsaltpack/archive/v0.3.2.tar.gz
          tar -xvzf v0.3.2.tar.gz
          pushd libsaltpack-0.3.2
          git clone https://github.com/983/Num.git ext/Num
          cmake -DCMAKE_CXX_FLAGS="-I ../boost_libs" .
          make
          sudo make install
          popd

      - name: Build
        run: |
          mvn compile
          cmake -DCMAKE_CXX_FLAGS="-I boost_libs" .
          make
          mvn exec:java -Dexec.mainClass="com.gherynos.libsaltpack.Loader"
          rm ${{ matrix.library }}
          mvn test

        env:
          JAVA_HOME: ${{ matrix.java_home }}

      - if: runner.os == 'Linux' && github.event_name == 'push'
        name: Coveralls report
        run: mvn jacoco:report coveralls:report -DrepoToken=${{ secrets.COVERALLS_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}.zip
          path: src/main/resources/lib/

  assemble:
    needs: unix
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Libraries path
        run: |
          mkdir -p src/main/resources/lib

      - uses: actions/download-artifact@v4
        with:
          name: ubuntu-22.04.zip
          path: src/main/resources/lib

      - uses: actions/download-artifact@v4
        with:
          name: macos-13.zip
          path: src/main/resources/lib

      - uses: actions/download-artifact@v4
        with:
          name: macos-14.zip
          path: src/main/resources/lib

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Package
        run: |
          mvn package

      - if: github.event_name == 'release'
        name: Publish
        run: |
          mvn --batch-mode deploy

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
